/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as OgDefaultRouteImport } from './routes/og.default'
import { Route as OgSlugRouteImport } from './routes/og.$slug'
import { Route as AuthedProvidersRouteImport } from './routes/_authed/providers'
import { Route as AuthedParentRouteImport } from './routes/_authed/parent'
import { Route as AuthedKidRouteImport } from './routes/_authed/kid'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedParentIndexRouteImport } from './routes/_authed/parent/index'
import { Route as AuthedKidIndexRouteImport } from './routes/_authed/kid/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedParentGuidesRouteImport } from './routes/_authed/parent/guides'
import { Route as AuthedKidQuizRouteImport } from './routes/_authed/kid/quiz'
import { Route as AuthedKidGuidesRouteImport } from './routes/_authed/kid/guides'
import { Route as AuthedKidCelebrationRouteImport } from './routes/_authed/kid/celebration'
import { Route as AuthedKidCardRouteImport } from './routes/_authed/kid/card'
import { Route as AuthedAdminContentRouteImport } from './routes/_authed/admin/content'
import { Route as AuthedAdminAdminsRouteImport } from './routes/_authed/admin/admins'
import { Route as AuthedAdminAccountsRouteImport } from './routes/_authed/admin/accounts'
import { Route as AuthedAdminContentIndexRouteImport } from './routes/_authed/admin/content/index'
import { Route as AuthedAdminAccountsIndexRouteImport } from './routes/_authed/admin/accounts.index'
import { Route as AuthedParentKidsChildIdRouteImport } from './routes/_authed/parent/kids.$childId'
import { Route as AuthedAdminContentTemplatesRouteImport } from './routes/_authed/admin/content/templates'
import { Route as AuthedAdminContentStoriesRouteImport } from './routes/_authed/admin/content/stories'
import { Route as AuthedAdminContentSetupRouteImport } from './routes/_authed/admin/content/setup'
import { Route as AuthedAdminContentQuizRouteImport } from './routes/_authed/admin/content/quiz'
import { Route as AuthedAdminContentProvidersRouteImport } from './routes/_authed/admin/content/providers'
import { Route as AuthedAdminContentPromptsRouteImport } from './routes/_authed/admin/content/prompts'
import { Route as AuthedAdminContentMilestonesRouteImport } from './routes/_authed/admin/content/milestones'
import { Route as AuthedAdminAccountsParentIdRouteImport } from './routes/_authed/admin/accounts.$parentId'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDefaultRoute = OgDefaultRouteImport.update({
  id: '/og/default',
  path: '/og/default',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSlugRoute = OgSlugRouteImport.update({
  id: '/og/$slug',
  path: '/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProvidersRoute = AuthedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentRoute = AuthedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKidRoute = AuthedKidRouteImport.update({
  id: '/kid',
  path: '/kid',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentIndexRoute = AuthedParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedKidIndexRoute = AuthedKidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedParentGuidesRoute = AuthedParentGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedKidQuizRoute = AuthedKidQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedKidGuidesRoute = AuthedKidGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedKidCelebrationRoute = AuthedKidCelebrationRouteImport.update({
  id: '/celebration',
  path: '/celebration',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedKidCardRoute = AuthedKidCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedAdminContentRoute = AuthedAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAdminsRoute = AuthedAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAccountsRoute = AuthedAdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminContentIndexRoute = AuthedAdminContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminContentRoute,
} as any)
const AuthedAdminAccountsIndexRoute =
  AuthedAdminAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdminAccountsRoute,
  } as any)
const AuthedParentKidsChildIdRoute = AuthedParentKidsChildIdRouteImport.update({
  id: '/kids/$childId',
  path: '/kids/$childId',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedAdminContentTemplatesRoute =
  AuthedAdminContentTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthedAdminContentRoute,
  } as any)
const AuthedAdminContentStoriesRoute =
  AuthedAdminContentStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthedAdminContentRoute,
  } as any)
const AuthedAdminContentSetupRoute = AuthedAdminContentSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedAdminContentRoute,
} as any)
const AuthedAdminContentQuizRoute = AuthedAdminContentQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthedAdminContentRoute,
} as any)
const AuthedAdminContentProvidersRoute =
  AuthedAdminContentProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthedAdminContentRoute,
  } as any)
const AuthedAdminContentPromptsRoute =
  AuthedAdminContentPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthedAdminContentRoute,
  } as any)
const AuthedAdminContentMilestonesRoute =
  AuthedAdminContentMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AuthedAdminContentRoute,
  } as any)
const AuthedAdminAccountsParentIdRoute =
  AuthedAdminAccountsParentIdRouteImport.update({
    id: '/$parentId',
    path: '/$parentId',
    getParentRoute: () => AuthedAdminAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/stories': typeof StoriesRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/kid': typeof AuthedKidRouteWithChildren
  '/parent': typeof AuthedParentRouteWithChildren
  '/providers': typeof AuthedProvidersRoute
  '/og/$slug': typeof OgSlugRoute
  '/og/default': typeof OgDefaultRoute
  '/share/$slug': typeof ShareSlugRoute
  '/admin/accounts': typeof AuthedAdminAccountsRouteWithChildren
  '/admin/admins': typeof AuthedAdminAdminsRoute
  '/admin/content': typeof AuthedAdminContentRouteWithChildren
  '/kid/card': typeof AuthedKidCardRoute
  '/kid/celebration': typeof AuthedKidCelebrationRoute
  '/kid/guides': typeof AuthedKidGuidesRoute
  '/kid/quiz': typeof AuthedKidQuizRoute
  '/parent/guides': typeof AuthedParentGuidesRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/kid/': typeof AuthedKidIndexRoute
  '/parent/': typeof AuthedParentIndexRoute
  '/admin/accounts/$parentId': typeof AuthedAdminAccountsParentIdRoute
  '/admin/content/milestones': typeof AuthedAdminContentMilestonesRoute
  '/admin/content/prompts': typeof AuthedAdminContentPromptsRoute
  '/admin/content/providers': typeof AuthedAdminContentProvidersRoute
  '/admin/content/quiz': typeof AuthedAdminContentQuizRoute
  '/admin/content/setup': typeof AuthedAdminContentSetupRoute
  '/admin/content/stories': typeof AuthedAdminContentStoriesRoute
  '/admin/content/templates': typeof AuthedAdminContentTemplatesRoute
  '/parent/kids/$childId': typeof AuthedParentKidsChildIdRoute
  '/admin/accounts/': typeof AuthedAdminAccountsIndexRoute
  '/admin/content/': typeof AuthedAdminContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/stories': typeof StoriesRoute
  '/providers': typeof AuthedProvidersRoute
  '/og/$slug': typeof OgSlugRoute
  '/og/default': typeof OgDefaultRoute
  '/share/$slug': typeof ShareSlugRoute
  '/admin/admins': typeof AuthedAdminAdminsRoute
  '/kid/card': typeof AuthedKidCardRoute
  '/kid/celebration': typeof AuthedKidCelebrationRoute
  '/kid/guides': typeof AuthedKidGuidesRoute
  '/kid/quiz': typeof AuthedKidQuizRoute
  '/parent/guides': typeof AuthedParentGuidesRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/kid': typeof AuthedKidIndexRoute
  '/parent': typeof AuthedParentIndexRoute
  '/admin/accounts/$parentId': typeof AuthedAdminAccountsParentIdRoute
  '/admin/content/milestones': typeof AuthedAdminContentMilestonesRoute
  '/admin/content/prompts': typeof AuthedAdminContentPromptsRoute
  '/admin/content/providers': typeof AuthedAdminContentProvidersRoute
  '/admin/content/quiz': typeof AuthedAdminContentQuizRoute
  '/admin/content/setup': typeof AuthedAdminContentSetupRoute
  '/admin/content/stories': typeof AuthedAdminContentStoriesRoute
  '/admin/content/templates': typeof AuthedAdminContentTemplatesRoute
  '/parent/kids/$childId': typeof AuthedParentKidsChildIdRoute
  '/admin/accounts': typeof AuthedAdminAccountsIndexRoute
  '/admin/content': typeof AuthedAdminContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/stories': typeof StoriesRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/kid': typeof AuthedKidRouteWithChildren
  '/_authed/parent': typeof AuthedParentRouteWithChildren
  '/_authed/providers': typeof AuthedProvidersRoute
  '/og/$slug': typeof OgSlugRoute
  '/og/default': typeof OgDefaultRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_authed/admin/accounts': typeof AuthedAdminAccountsRouteWithChildren
  '/_authed/admin/admins': typeof AuthedAdminAdminsRoute
  '/_authed/admin/content': typeof AuthedAdminContentRouteWithChildren
  '/_authed/kid/card': typeof AuthedKidCardRoute
  '/_authed/kid/celebration': typeof AuthedKidCelebrationRoute
  '/_authed/kid/guides': typeof AuthedKidGuidesRoute
  '/_authed/kid/quiz': typeof AuthedKidQuizRoute
  '/_authed/parent/guides': typeof AuthedParentGuidesRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/kid/': typeof AuthedKidIndexRoute
  '/_authed/parent/': typeof AuthedParentIndexRoute
  '/_authed/admin/accounts/$parentId': typeof AuthedAdminAccountsParentIdRoute
  '/_authed/admin/content/milestones': typeof AuthedAdminContentMilestonesRoute
  '/_authed/admin/content/prompts': typeof AuthedAdminContentPromptsRoute
  '/_authed/admin/content/providers': typeof AuthedAdminContentProvidersRoute
  '/_authed/admin/content/quiz': typeof AuthedAdminContentQuizRoute
  '/_authed/admin/content/setup': typeof AuthedAdminContentSetupRoute
  '/_authed/admin/content/stories': typeof AuthedAdminContentStoriesRoute
  '/_authed/admin/content/templates': typeof AuthedAdminContentTemplatesRoute
  '/_authed/parent/kids/$childId': typeof AuthedParentKidsChildIdRoute
  '/_authed/admin/accounts/': typeof AuthedAdminAccountsIndexRoute
  '/_authed/admin/content/': typeof AuthedAdminContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/site.webmanifest'
    | '/stories'
    | '/admin'
    | '/kid'
    | '/parent'
    | '/providers'
    | '/og/$slug'
    | '/og/default'
    | '/share/$slug'
    | '/admin/accounts'
    | '/admin/admins'
    | '/admin/content'
    | '/kid/card'
    | '/kid/celebration'
    | '/kid/guides'
    | '/kid/quiz'
    | '/parent/guides'
    | '/admin/'
    | '/kid/'
    | '/parent/'
    | '/admin/accounts/$parentId'
    | '/admin/content/milestones'
    | '/admin/content/prompts'
    | '/admin/content/providers'
    | '/admin/content/quiz'
    | '/admin/content/setup'
    | '/admin/content/stories'
    | '/admin/content/templates'
    | '/parent/kids/$childId'
    | '/admin/accounts/'
    | '/admin/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/site.webmanifest'
    | '/stories'
    | '/providers'
    | '/og/$slug'
    | '/og/default'
    | '/share/$slug'
    | '/admin/admins'
    | '/kid/card'
    | '/kid/celebration'
    | '/kid/guides'
    | '/kid/quiz'
    | '/parent/guides'
    | '/admin'
    | '/kid'
    | '/parent'
    | '/admin/accounts/$parentId'
    | '/admin/content/milestones'
    | '/admin/content/prompts'
    | '/admin/content/providers'
    | '/admin/content/quiz'
    | '/admin/content/setup'
    | '/admin/content/stories'
    | '/admin/content/templates'
    | '/parent/kids/$childId'
    | '/admin/accounts'
    | '/admin/content'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/site.webmanifest'
    | '/stories'
    | '/_authed/admin'
    | '/_authed/kid'
    | '/_authed/parent'
    | '/_authed/providers'
    | '/og/$slug'
    | '/og/default'
    | '/share/$slug'
    | '/_authed/admin/accounts'
    | '/_authed/admin/admins'
    | '/_authed/admin/content'
    | '/_authed/kid/card'
    | '/_authed/kid/celebration'
    | '/_authed/kid/guides'
    | '/_authed/kid/quiz'
    | '/_authed/parent/guides'
    | '/_authed/admin/'
    | '/_authed/kid/'
    | '/_authed/parent/'
    | '/_authed/admin/accounts/$parentId'
    | '/_authed/admin/content/milestones'
    | '/_authed/admin/content/prompts'
    | '/_authed/admin/content/providers'
    | '/_authed/admin/content/quiz'
    | '/_authed/admin/content/setup'
    | '/_authed/admin/content/stories'
    | '/_authed/admin/content/templates'
    | '/_authed/parent/kids/$childId'
    | '/_authed/admin/accounts/'
    | '/_authed/admin/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  StoriesRoute: typeof StoriesRoute
  OgSlugRoute: typeof OgSlugRoute
  OgDefaultRoute: typeof OgDefaultRoute
  ShareSlugRoute: typeof ShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/default': {
      id: '/og/default'
      path: '/og/default'
      fullPath: '/og/default'
      preLoaderRoute: typeof OgDefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$slug': {
      id: '/og/$slug'
      path: '/og/$slug'
      fullPath: '/og/$slug'
      preLoaderRoute: typeof OgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/providers': {
      id: '/_authed/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthedProvidersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent': {
      id: '/_authed/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthedParentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kid': {
      id: '/_authed/kid'
      path: '/kid'
      fullPath: '/kid'
      preLoaderRoute: typeof AuthedKidRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent/': {
      id: '/_authed/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthedParentIndexRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/kid/': {
      id: '/_authed/kid/'
      path: '/'
      fullPath: '/kid/'
      preLoaderRoute: typeof AuthedKidIndexRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/parent/guides': {
      id: '/_authed/parent/guides'
      path: '/guides'
      fullPath: '/parent/guides'
      preLoaderRoute: typeof AuthedParentGuidesRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/kid/quiz': {
      id: '/_authed/kid/quiz'
      path: '/quiz'
      fullPath: '/kid/quiz'
      preLoaderRoute: typeof AuthedKidQuizRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/kid/guides': {
      id: '/_authed/kid/guides'
      path: '/guides'
      fullPath: '/kid/guides'
      preLoaderRoute: typeof AuthedKidGuidesRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/kid/celebration': {
      id: '/_authed/kid/celebration'
      path: '/celebration'
      fullPath: '/kid/celebration'
      preLoaderRoute: typeof AuthedKidCelebrationRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/kid/card': {
      id: '/_authed/kid/card'
      path: '/card'
      fullPath: '/kid/card'
      preLoaderRoute: typeof AuthedKidCardRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/admin/content': {
      id: '/_authed/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthedAdminContentRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/admins': {
      id: '/_authed/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthedAdminAdminsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/accounts': {
      id: '/_authed/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthedAdminAccountsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/content/': {
      id: '/_authed/admin/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AuthedAdminContentIndexRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/accounts/': {
      id: '/_authed/admin/accounts/'
      path: '/'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AuthedAdminAccountsIndexRouteImport
      parentRoute: typeof AuthedAdminAccountsRoute
    }
    '/_authed/parent/kids/$childId': {
      id: '/_authed/parent/kids/$childId'
      path: '/kids/$childId'
      fullPath: '/parent/kids/$childId'
      preLoaderRoute: typeof AuthedParentKidsChildIdRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/admin/content/templates': {
      id: '/_authed/admin/content/templates'
      path: '/templates'
      fullPath: '/admin/content/templates'
      preLoaderRoute: typeof AuthedAdminContentTemplatesRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/content/stories': {
      id: '/_authed/admin/content/stories'
      path: '/stories'
      fullPath: '/admin/content/stories'
      preLoaderRoute: typeof AuthedAdminContentStoriesRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/content/setup': {
      id: '/_authed/admin/content/setup'
      path: '/setup'
      fullPath: '/admin/content/setup'
      preLoaderRoute: typeof AuthedAdminContentSetupRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/content/quiz': {
      id: '/_authed/admin/content/quiz'
      path: '/quiz'
      fullPath: '/admin/content/quiz'
      preLoaderRoute: typeof AuthedAdminContentQuizRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/content/providers': {
      id: '/_authed/admin/content/providers'
      path: '/providers'
      fullPath: '/admin/content/providers'
      preLoaderRoute: typeof AuthedAdminContentProvidersRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/content/prompts': {
      id: '/_authed/admin/content/prompts'
      path: '/prompts'
      fullPath: '/admin/content/prompts'
      preLoaderRoute: typeof AuthedAdminContentPromptsRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/content/milestones': {
      id: '/_authed/admin/content/milestones'
      path: '/milestones'
      fullPath: '/admin/content/milestones'
      preLoaderRoute: typeof AuthedAdminContentMilestonesRouteImport
      parentRoute: typeof AuthedAdminContentRoute
    }
    '/_authed/admin/accounts/$parentId': {
      id: '/_authed/admin/accounts/$parentId'
      path: '/$parentId'
      fullPath: '/admin/accounts/$parentId'
      preLoaderRoute: typeof AuthedAdminAccountsParentIdRouteImport
      parentRoute: typeof AuthedAdminAccountsRoute
    }
  }
}

interface AuthedAdminAccountsRouteChildren {
  AuthedAdminAccountsParentIdRoute: typeof AuthedAdminAccountsParentIdRoute
  AuthedAdminAccountsIndexRoute: typeof AuthedAdminAccountsIndexRoute
}

const AuthedAdminAccountsRouteChildren: AuthedAdminAccountsRouteChildren = {
  AuthedAdminAccountsParentIdRoute: AuthedAdminAccountsParentIdRoute,
  AuthedAdminAccountsIndexRoute: AuthedAdminAccountsIndexRoute,
}

const AuthedAdminAccountsRouteWithChildren =
  AuthedAdminAccountsRoute._addFileChildren(AuthedAdminAccountsRouteChildren)

interface AuthedAdminContentRouteChildren {
  AuthedAdminContentMilestonesRoute: typeof AuthedAdminContentMilestonesRoute
  AuthedAdminContentPromptsRoute: typeof AuthedAdminContentPromptsRoute
  AuthedAdminContentProvidersRoute: typeof AuthedAdminContentProvidersRoute
  AuthedAdminContentQuizRoute: typeof AuthedAdminContentQuizRoute
  AuthedAdminContentSetupRoute: typeof AuthedAdminContentSetupRoute
  AuthedAdminContentStoriesRoute: typeof AuthedAdminContentStoriesRoute
  AuthedAdminContentTemplatesRoute: typeof AuthedAdminContentTemplatesRoute
  AuthedAdminContentIndexRoute: typeof AuthedAdminContentIndexRoute
}

const AuthedAdminContentRouteChildren: AuthedAdminContentRouteChildren = {
  AuthedAdminContentMilestonesRoute: AuthedAdminContentMilestonesRoute,
  AuthedAdminContentPromptsRoute: AuthedAdminContentPromptsRoute,
  AuthedAdminContentProvidersRoute: AuthedAdminContentProvidersRoute,
  AuthedAdminContentQuizRoute: AuthedAdminContentQuizRoute,
  AuthedAdminContentSetupRoute: AuthedAdminContentSetupRoute,
  AuthedAdminContentStoriesRoute: AuthedAdminContentStoriesRoute,
  AuthedAdminContentTemplatesRoute: AuthedAdminContentTemplatesRoute,
  AuthedAdminContentIndexRoute: AuthedAdminContentIndexRoute,
}

const AuthedAdminContentRouteWithChildren =
  AuthedAdminContentRoute._addFileChildren(AuthedAdminContentRouteChildren)

interface AuthedAdminRouteChildren {
  AuthedAdminAccountsRoute: typeof AuthedAdminAccountsRouteWithChildren
  AuthedAdminAdminsRoute: typeof AuthedAdminAdminsRoute
  AuthedAdminContentRoute: typeof AuthedAdminContentRouteWithChildren
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminAccountsRoute: AuthedAdminAccountsRouteWithChildren,
  AuthedAdminAdminsRoute: AuthedAdminAdminsRoute,
  AuthedAdminContentRoute: AuthedAdminContentRouteWithChildren,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedKidRouteChildren {
  AuthedKidCardRoute: typeof AuthedKidCardRoute
  AuthedKidCelebrationRoute: typeof AuthedKidCelebrationRoute
  AuthedKidGuidesRoute: typeof AuthedKidGuidesRoute
  AuthedKidQuizRoute: typeof AuthedKidQuizRoute
  AuthedKidIndexRoute: typeof AuthedKidIndexRoute
}

const AuthedKidRouteChildren: AuthedKidRouteChildren = {
  AuthedKidCardRoute: AuthedKidCardRoute,
  AuthedKidCelebrationRoute: AuthedKidCelebrationRoute,
  AuthedKidGuidesRoute: AuthedKidGuidesRoute,
  AuthedKidQuizRoute: AuthedKidQuizRoute,
  AuthedKidIndexRoute: AuthedKidIndexRoute,
}

const AuthedKidRouteWithChildren = AuthedKidRoute._addFileChildren(
  AuthedKidRouteChildren,
)

interface AuthedParentRouteChildren {
  AuthedParentGuidesRoute: typeof AuthedParentGuidesRoute
  AuthedParentIndexRoute: typeof AuthedParentIndexRoute
  AuthedParentKidsChildIdRoute: typeof AuthedParentKidsChildIdRoute
}

const AuthedParentRouteChildren: AuthedParentRouteChildren = {
  AuthedParentGuidesRoute: AuthedParentGuidesRoute,
  AuthedParentIndexRoute: AuthedParentIndexRoute,
  AuthedParentKidsChildIdRoute: AuthedParentKidsChildIdRoute,
}

const AuthedParentRouteWithChildren = AuthedParentRoute._addFileChildren(
  AuthedParentRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedKidRoute: typeof AuthedKidRouteWithChildren
  AuthedParentRoute: typeof AuthedParentRouteWithChildren
  AuthedProvidersRoute: typeof AuthedProvidersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedKidRoute: AuthedKidRouteWithChildren,
  AuthedParentRoute: AuthedParentRouteWithChildren,
  AuthedProvidersRoute: AuthedProvidersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  StoriesRoute: StoriesRoute,
  OgSlugRoute: OgSlugRoute,
  OgDefaultRoute: OgDefaultRoute,
  ShareSlugRoute: ShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
