/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProvidersRouteImport } from './routes/_authed/providers'
import { Route as AuthedParentRouteImport } from './routes/_authed/parent'
import { Route as AuthedKidRouteImport } from './routes/_authed/kid'
import { Route as AuthedParentIndexRouteImport } from './routes/_authed/parent/index'
import { Route as AuthedKidIndexRouteImport } from './routes/_authed/kid/index'
import { Route as AuthedParentGuidesRouteImport } from './routes/_authed/parent/guides'
import { Route as AuthedKidQuizRouteImport } from './routes/_authed/kid/quiz'
import { Route as AuthedKidGuidesRouteImport } from './routes/_authed/kid/guides'
import { Route as AuthedKidCelebrationRouteImport } from './routes/_authed/kid/celebration'
import { Route as AuthedKidCardRouteImport } from './routes/_authed/kid/card'
import { Route as AuthedParentKidsChildIdRouteImport } from './routes/_authed/parent/kids.$childId'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProvidersRoute = AuthedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentRoute = AuthedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKidRoute = AuthedKidRouteImport.update({
  id: '/kid',
  path: '/kid',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentIndexRoute = AuthedParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedKidIndexRoute = AuthedKidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedParentGuidesRoute = AuthedParentGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedKidQuizRoute = AuthedKidQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedKidGuidesRoute = AuthedKidGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedKidCelebrationRoute = AuthedKidCelebrationRouteImport.update({
  id: '/celebration',
  path: '/celebration',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedKidCardRoute = AuthedKidCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AuthedKidRoute,
} as any)
const AuthedParentKidsChildIdRoute = AuthedParentKidsChildIdRouteImport.update({
  id: '/kids/$childId',
  path: '/kids/$childId',
  getParentRoute: () => AuthedParentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/kid': typeof AuthedKidRouteWithChildren
  '/parent': typeof AuthedParentRouteWithChildren
  '/providers': typeof AuthedProvidersRoute
  '/kid/card': typeof AuthedKidCardRoute
  '/kid/celebration': typeof AuthedKidCelebrationRoute
  '/kid/guides': typeof AuthedKidGuidesRoute
  '/kid/quiz': typeof AuthedKidQuizRoute
  '/parent/guides': typeof AuthedParentGuidesRoute
  '/kid/': typeof AuthedKidIndexRoute
  '/parent/': typeof AuthedParentIndexRoute
  '/parent/kids/$childId': typeof AuthedParentKidsChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/providers': typeof AuthedProvidersRoute
  '/kid/card': typeof AuthedKidCardRoute
  '/kid/celebration': typeof AuthedKidCelebrationRoute
  '/kid/guides': typeof AuthedKidGuidesRoute
  '/kid/quiz': typeof AuthedKidQuizRoute
  '/parent/guides': typeof AuthedParentGuidesRoute
  '/kid': typeof AuthedKidIndexRoute
  '/parent': typeof AuthedParentIndexRoute
  '/parent/kids/$childId': typeof AuthedParentKidsChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/_authed/kid': typeof AuthedKidRouteWithChildren
  '/_authed/parent': typeof AuthedParentRouteWithChildren
  '/_authed/providers': typeof AuthedProvidersRoute
  '/_authed/kid/card': typeof AuthedKidCardRoute
  '/_authed/kid/celebration': typeof AuthedKidCelebrationRoute
  '/_authed/kid/guides': typeof AuthedKidGuidesRoute
  '/_authed/kid/quiz': typeof AuthedKidQuizRoute
  '/_authed/parent/guides': typeof AuthedParentGuidesRoute
  '/_authed/kid/': typeof AuthedKidIndexRoute
  '/_authed/parent/': typeof AuthedParentIndexRoute
  '/_authed/parent/kids/$childId': typeof AuthedParentKidsChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/stories'
    | '/kid'
    | '/parent'
    | '/providers'
    | '/kid/card'
    | '/kid/celebration'
    | '/kid/guides'
    | '/kid/quiz'
    | '/parent/guides'
    | '/kid/'
    | '/parent/'
    | '/parent/kids/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/stories'
    | '/providers'
    | '/kid/card'
    | '/kid/celebration'
    | '/kid/guides'
    | '/kid/quiz'
    | '/parent/guides'
    | '/kid'
    | '/parent'
    | '/parent/kids/$childId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/stories'
    | '/_authed/kid'
    | '/_authed/parent'
    | '/_authed/providers'
    | '/_authed/kid/card'
    | '/_authed/kid/celebration'
    | '/_authed/kid/guides'
    | '/_authed/kid/quiz'
    | '/_authed/parent/guides'
    | '/_authed/kid/'
    | '/_authed/parent/'
    | '/_authed/parent/kids/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/providers': {
      id: '/_authed/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthedProvidersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent': {
      id: '/_authed/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthedParentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kid': {
      id: '/_authed/kid'
      path: '/kid'
      fullPath: '/kid'
      preLoaderRoute: typeof AuthedKidRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent/': {
      id: '/_authed/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthedParentIndexRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/kid/': {
      id: '/_authed/kid/'
      path: '/'
      fullPath: '/kid/'
      preLoaderRoute: typeof AuthedKidIndexRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/parent/guides': {
      id: '/_authed/parent/guides'
      path: '/guides'
      fullPath: '/parent/guides'
      preLoaderRoute: typeof AuthedParentGuidesRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/kid/quiz': {
      id: '/_authed/kid/quiz'
      path: '/quiz'
      fullPath: '/kid/quiz'
      preLoaderRoute: typeof AuthedKidQuizRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/kid/guides': {
      id: '/_authed/kid/guides'
      path: '/guides'
      fullPath: '/kid/guides'
      preLoaderRoute: typeof AuthedKidGuidesRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/kid/celebration': {
      id: '/_authed/kid/celebration'
      path: '/celebration'
      fullPath: '/kid/celebration'
      preLoaderRoute: typeof AuthedKidCelebrationRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/kid/card': {
      id: '/_authed/kid/card'
      path: '/card'
      fullPath: '/kid/card'
      preLoaderRoute: typeof AuthedKidCardRouteImport
      parentRoute: typeof AuthedKidRoute
    }
    '/_authed/parent/kids/$childId': {
      id: '/_authed/parent/kids/$childId'
      path: '/kids/$childId'
      fullPath: '/parent/kids/$childId'
      preLoaderRoute: typeof AuthedParentKidsChildIdRouteImport
      parentRoute: typeof AuthedParentRoute
    }
  }
}

interface AuthedKidRouteChildren {
  AuthedKidCardRoute: typeof AuthedKidCardRoute
  AuthedKidCelebrationRoute: typeof AuthedKidCelebrationRoute
  AuthedKidGuidesRoute: typeof AuthedKidGuidesRoute
  AuthedKidQuizRoute: typeof AuthedKidQuizRoute
  AuthedKidIndexRoute: typeof AuthedKidIndexRoute
}

const AuthedKidRouteChildren: AuthedKidRouteChildren = {
  AuthedKidCardRoute: AuthedKidCardRoute,
  AuthedKidCelebrationRoute: AuthedKidCelebrationRoute,
  AuthedKidGuidesRoute: AuthedKidGuidesRoute,
  AuthedKidQuizRoute: AuthedKidQuizRoute,
  AuthedKidIndexRoute: AuthedKidIndexRoute,
}

const AuthedKidRouteWithChildren = AuthedKidRoute._addFileChildren(
  AuthedKidRouteChildren,
)

interface AuthedParentRouteChildren {
  AuthedParentGuidesRoute: typeof AuthedParentGuidesRoute
  AuthedParentIndexRoute: typeof AuthedParentIndexRoute
  AuthedParentKidsChildIdRoute: typeof AuthedParentKidsChildIdRoute
}

const AuthedParentRouteChildren: AuthedParentRouteChildren = {
  AuthedParentGuidesRoute: AuthedParentGuidesRoute,
  AuthedParentIndexRoute: AuthedParentIndexRoute,
  AuthedParentKidsChildIdRoute: AuthedParentKidsChildIdRoute,
}

const AuthedParentRouteWithChildren = AuthedParentRoute._addFileChildren(
  AuthedParentRouteChildren,
)

interface AuthedRouteChildren {
  AuthedKidRoute: typeof AuthedKidRouteWithChildren
  AuthedParentRoute: typeof AuthedParentRouteWithChildren
  AuthedProvidersRoute: typeof AuthedProvidersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedKidRoute: AuthedKidRouteWithChildren,
  AuthedParentRoute: AuthedParentRouteWithChildren,
  AuthedProvidersRoute: AuthedProvidersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
