import type { QuoteEntry } from "@/lib/types";

/**
 * A deliberately conservative expansion of the runtime quotation catalog.
 *
 * These are either short passages from public-domain ancient texts in an
 * original project translation, or public-domain English-language works.
 * `sectionIds` records actual editorial placement approval; it is not a list
 * of every section where a quotation could conceivably fit.
 */
export const expandedQuoteCatalog: QuoteEntry[] = [
  { id: "q-genesis-image", text: "God created the human being in the divine image.", author: "Genesis 1:27", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "interfaith", "social-justice", "lgbtq", "feminist"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Genesis.1.27", approved: true },
  { id: "q-genesis-keeper", text: "Am I my sibling’s keeper?", author: "Genesis 4:9", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "family-storytelling", "interfaith"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Genesis.4.9", approved: true },
  { id: "q-genesis-hospitality", text: "Let a little water be brought; wash your feet, and rest beneath the tree.", author: "Genesis 18:4", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "interfaith", "family-storytelling"], sectionIds: ["kadesh"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Genesis.18.4", approved: true },
  { id: "q-exodus-midwives", text: "The midwives honored God and did not do as the king of Egypt had ordered; they kept the children alive.", author: "Exodus 1:17", work: "Hebrew Bible", year: "Original project translation", themes: ["feminist", "social-justice", "traditional"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Exodus.1.17", approved: true },
  { id: "q-exodus-moses-turned", text: "Moses said: I will turn aside and see this great sight.", author: "Exodus 3:3", work: "Hebrew Bible", year: "Original project translation", themes: ["mindfulness", "traditional", "environment"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Exodus.3.3", approved: true },
  { id: "q-exodus-cry", text: "I have surely seen the suffering of my people in Egypt, and I have heard their cry.", author: "Exodus 3:7", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "traditional", "interfaith"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Exodus.3.7", approved: true },
  { id: "q-exodus-let-go", text: "Let my people go, so that they may serve me.", author: "Exodus 5:1", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "social-justice"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Exodus.5.1", approved: true },
  { id: "q-exodus-strength", text: "The Eternal is my strength and my song, and has become my deliverance.", author: "Exodus 15:2", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "mindfulness"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Exodus.15.2", approved: true },
  { id: "q-leviticus-neighbor", text: "Love your neighbor as yourself.", author: "Leviticus 19:18", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "interfaith", "social-justice", "lgbtq", "family-storytelling"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Leviticus.19.18", approved: true },
  { id: "q-leviticus-stranger", text: "The stranger who lives with you shall be as a citizen among you; love them as yourself, for you were strangers in Egypt.", author: "Leviticus 19:34", work: "Hebrew Bible", year: "Original project translation", themes: ["interfaith", "social-justice", "traditional"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Leviticus.19.34", approved: true },
  { id: "q-deuteronomy-justice", text: "Justice, justice shall you pursue.", author: "Deuteronomy 16:20", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "traditional", "feminist", "lgbtq"], sectionIds: ["maggid", "nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Deuteronomy.16.20", approved: true },
  { id: "q-deuteronomy-open-hand", text: "You shall surely open your hand to your sibling, to the poor and the needy in your land.", author: "Deuteronomy 15:11", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "traditional", "interfaith"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Deuteronomy.15.11", approved: true },
  { id: "q-deuteronomy-remember", text: "Remember that you were enslaved in Egypt, and that the Eternal your God redeemed you from there.", author: "Deuteronomy 24:18", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "family-storytelling", "social-justice"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Deuteronomy.24.18", approved: true },
  { id: "q-deuteronomy-life", text: "Choose life, so that you and your descendants may live.", author: "Deuteronomy 30:19", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "family-storytelling", "environment", "mindfulness"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Deuteronomy.30.19", approved: true },
  { id: "q-psalm-peace", text: "Seek peace and pursue it.", author: "Psalm 34:15", work: "Hebrew Bible", year: "Original project translation", themes: ["traditional", "interfaith", "social-justice", "mindfulness"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Psalms.34.15", approved: true },
  { id: "q-psalm-goodness", text: "The earth is full of the Eternal’s goodness.", author: "Psalm 33:5", work: "Hebrew Bible", year: "Original project translation", themes: ["environment", "traditional", "mindfulness"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Psalms.33.5", approved: true },
  { id: "q-psalm-justice", text: "Righteousness and justice are the foundation of your throne; steadfast love and truth go before you.", author: "Psalm 89:15", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "traditional", "interfaith"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Psalms.89.15", approved: true },
  { id: "q-psalm-together", text: "How good and pleasant it is when kindred dwell together.", author: "Psalm 133:1", work: "Hebrew Bible", year: "Original project translation", themes: ["family-storytelling", "interfaith", "lgbtq", "traditional"], sectionIds: ["kadesh", "nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Psalms.133.1", approved: true },
  { id: "q-proverbs-voiceless", text: "Open your mouth for those without a voice, for the rights of all who are vulnerable.", author: "Proverbs 31:8", work: "Hebrew Bible", year: "Original project translation", themes: ["feminist", "social-justice", "traditional"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Proverbs.31.8", approved: true },
  { id: "q-proverbs-tree", text: "It is a tree of life to those who hold fast to it.", author: "Proverbs 3:18", work: "Hebrew Bible", year: "Original project translation", themes: ["environment", "traditional", "mindfulness"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Proverbs.3.18", approved: true },
  { id: "q-isaiah-learn-good", text: "Learn to do good; seek justice, strengthen the oppressed, defend the orphan, and plead for the widow.", author: "Isaiah 1:17", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "feminist", "traditional"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Isaiah.1.17", approved: true },
  { id: "q-isaiah-repairer", text: "You shall be called the repairer of the breach, the restorer of paths for people to live in.", author: "Isaiah 58:12", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "environment", "traditional"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Isaiah.58.12", approved: true },
  { id: "q-jeremiah-welfare", text: "Seek the welfare of the city where I have sent you, and pray for it, for in its welfare you will find your welfare.", author: "Jeremiah 29:7", work: "Hebrew Bible", year: "Original project translation", themes: ["interfaith", "social-justice", "traditional"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Jeremiah.29.7", approved: true },
  { id: "q-amos-waters", text: "Let justice roll down like waters, and righteousness like an ever-flowing stream.", author: "Amos 5:24", work: "Hebrew Bible", year: "Original project translation", themes: ["social-justice", "environment", "traditional"], sectionIds: ["maggid", "nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Amos.5.24", approved: true },
  { id: "q-malachi-parent", text: "Do we not all have one parent? Did not one God create us?", author: "Malachi 2:10", work: "Hebrew Bible", year: "Original project translation", themes: ["interfaith", "social-justice", "family-storytelling", "traditional"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Malachi.2.10", approved: true },
  { id: "q-avot-precious", text: "Beloved is the human being, created in the divine image.", author: "Rabbi Akiva", work: "Pirkei Avot 3:14", year: "Original project translation", themes: ["traditional", "interfaith", "social-justice", "lgbtq", "feminist"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Pirkei_Avot.3.14", approved: true },
  { id: "q-avot-welcome", text: "Receive every person with a cheerful face.", author: "Shammai", work: "Pirkei Avot 1:15", year: "Original project translation", themes: ["family-storytelling", "interfaith", "traditional"], sectionIds: ["kadesh"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Pirkei_Avot.1.15", approved: true },
  { id: "q-avot-action", text: "Study is not the main thing; action is.", author: "Shimon ben Gamliel", work: "Pirkei Avot 1:17", year: "Original project translation", themes: ["traditional", "social-justice", "secular"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Pirkei_Avot.1.17", approved: true },
  { id: "q-avot-community", text: "Do not separate yourself from the community.", author: "Hillel", work: "Pirkei Avot 2:4", year: "Original project translation", themes: ["family-storytelling", "interfaith", "social-justice", "traditional"], sectionIds: ["kadesh", "nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Pirkei_Avot.2.4", approved: true },
  { id: "q-avot-freedom", text: "Read not ‘engraved’ but ‘freedom,’ for no one is free except the one who engages in learning.", author: "Rabbi Yehoshua ben Levi", work: "Pirkei Avot 6:2", year: "Original project translation", themes: ["traditional", "secular", "social-justice"], sectionIds: ["maggid"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Pirkei_Avot.6.2", approved: true },
  { id: "q-ecclesiastes-season", text: "For everything there is a season, and a time for every purpose under heaven.", author: "Ecclesiastes 3:1", work: "Hebrew Bible", year: "Original project translation", themes: ["mindfulness", "environment", "traditional", "secular"], sectionIds: ["kadesh", "nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Ecclesiastes.3.1", approved: true },
  { id: "q-ecclesiastes-two", text: "Two are better than one, because they have a good reward for their labor.", author: "Ecclesiastes 4:9", work: "Hebrew Bible", year: "Original project translation", themes: ["family-storytelling", "interfaith", "social-justice", "secular"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Ecclesiastes.4.9", approved: true },
  { id: "q-ruth-go", text: "Where you go, I will go; where you stay, I will stay. Your people shall be my people.", author: "Ruth 1:16", work: "Hebrew Bible", year: "Original project translation", themes: ["family-storytelling", "interfaith", "lgbtq", "feminist"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Ruth.1.16", approved: true },
  { id: "q-song-love", text: "Love is strong as death; its flame is a mighty flame.", author: "Song of Songs 8:6", work: "Hebrew Bible", year: "Original project translation", themes: ["lgbtq", "feminist", "family-storytelling", "traditional"], sectionIds: ["nirtzah"], rights: "original-translation", sourceUrl: "https://www.sefaria.org/Song_of_Songs.8.6", approved: true },
];
