import type { ContentCardItem } from "@/components/ContentCard";

export const culture: ContentCardItem[] = [
  {
    title: "What Jewish humor actually is, according to people who study it",
    source: "Hey Alma",
    url: "https://www.heyalma.com/",
    kind: "Read",
    image: "/images/culture/humor.jpg",
  },
  {
    title: "The best Jewish podcasts that aren't about being Jewish",
    source: "Kveller",
    url: "https://www.kveller.com/",
    kind: "Listen",
    image: "/images/culture/podcasts.jpg",
  },
  {
    title: "A very complete ranking of bagel toppings",
    source: "The Nosher",
    url: "https://www.myjewishlearning.com/the-nosher/",
    kind: "Read",
    image: "/images/culture/bagels.png",
  },
  {
    title: "Books to read if your only Jewish education was a bar mitzvah",
    source: "Tablet",
    url: "https://www.tabletmag.com/",
    kind: "Read",
    image: "/images/culture/books.jpg",
  },
  {
    title: "Shows with unmistakably Jewish characters that never make a big deal of it",
    source: "JTA",
    url: "https://www.jta.org/",
    kind: "Watch",
    image: "/images/culture/shows.jpg",
  },
  {
    title: "Deli culture, explained by the people who run the delis",
    source: "The Nosher",
    url: "https://www.myjewishlearning.com/the-nosher/",
    kind: "Read",
    image: "/images/culture/deli.jpg",
  },
  {
    title: "Stand-up specials with a distinct Jewish sensibility, ranked",
    source: "Hey Alma",
    url: "https://www.heyalma.com/",
    kind: "Watch",
    image: "/images/culture/standup.jpg",
  },
  {
    title: "Where Jewish food writing is actually going right now",
    source: "Tablet",
    url: "https://www.tabletmag.com/",
    kind: "Listen",
    image: "/images/culture/food-writing.jpg",
  },
  {
    title: "The time a New Yorker writer had to write his own Purim skit",
    source: "The New Yorker",
    url: "https://www.newyorker.com/magazine/2002/02/18/a-purim-story",
    kind: "Read",
    image: "/images/culture/purim-story.jpg",
  },
  {
    title: "Vogue has a name for the denim-skirt-and-loafers uniform you grew up around",
    source: "Vogue",
    url: "https://www.vogue.com/article/torah-teacher-aesthetic",
    kind: "Read",
    image: "/images/culture/fashion.jpg",
  },
  {
    title: "The Jewish sandwiches that made New York's ultimate sandwich list",
    source: "The New York Times",
    url: "https://www.nytimes.com/interactive/2024/dining/best-nyc-sandwiches.html",
    kind: "Read",
    image: "/images/culture/sandwiches.jpg",
  },
  {
    title: "The TikToker who turned loving trees into a whole Jewish thing",
    source: "@jewslovetrees on TikTok",
    url: "https://www.tiktok.com/@jewslovetrees",
    kind: "Watch",
    image: "/images/culture/trees.jpg",
  },
  {
    title: "Family recipes and the migration stories baked into them",
    source: "Jewish Food Society",
    url: "https://www.jewishfoodsociety.org/",
    kind: "Read",
    image: "/images/culture/recipes.jpg",
  },
  {
    title: "A million rescued Yiddish books, and the world inside them",
    source: "Yiddish Book Center",
    url: "https://www.yiddishbookcenter.org/",
    kind: "Read",
    image: "/images/culture/yiddish.jpg",
  },
  {
    title: "Daf Reactions: the Talmud, recapped like reality TV",
    source: "Miriam Anzovin on YouTube",
    url: "https://www.youtube.com/miriamanzovin",
    kind: "Watch",
    image: "/images/culture/talmud.jpg",
  },
  {
    title: "Why Chinese food on Christmas became a whole Jewish institution",
    source: "Smithsonian Magazine",
    url: "https://www.smithsonianmag.com/arts-culture/why-did-jewish-communities-take-to-chinese-food-11199092/",
    kind: "Read",
    image: "/images/culture/chinese-food.jpg",
  },
];
